title: Kevin DeLoach
description: Software Engineer, Philadelphia, PA
repository: kdeloach/kdeloach.github.io

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://kdeloach.me

baseurl: ""

permalink: /:slug/

collections:
   pages:
     output: true
     permalink: /:path/

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Dockerfile
  - docker-compose.yml
  - bin/
  - node_modules/
  - Makefile
  - webpack.config.js
  - "*.yml"
  - "*.json"
  - "*.lock"
