baseURL = 'https://kdeloach.me/'
languageCode = 'en-us'
title = 'Kevin DeLoach'

enableGitInfo = true
enableRobotsTXT = true
disableKinds = ['taxonomy', 'term', 'section']
cleanDestinationDir = true

[author]
  name = "Kevin DeLoach"
  email = "kdeloach@gmail.com"

[params]
  description = 'Software Engineer, Philadelphia, PA'
  repository = 'https://github.com/kdeloach/kdeloach.github.io'

[permalinks]
  posts = '/:slug/'

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = 'lovelace'
    tabWidth = 4

[markup.goldmark.renderer]
  unsafe = true

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"
