version: "3.9"

services:
  jekyll:
    build:
      context: .
      dockerfile: Dockerfile.jekyll
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - .:/srv/jekyll
    command: >
      serve --host 0.0.0.0 --port 4000 --drafts
      --livereload --livereload-port 35729
