version: "3.9"

services:
  hugo:
    build:
      context: .
      dockerfile: Dockerfile.hugo
    ports:
      - "1313:1313"
      - "35729:35729"
    volumes:
      - .:/srv/app
    command: hugo server -D --bind 0.0.0.0
  webpack:
    build:
      context: .
      dockerfile: Dockerfile.webpack
    volumes:
      - .:/usr/src/app
    command: build --watch
