FROM alpine:3.15.0


# libstdc++ gcompat are for hugo "extended" SASS/SCSS support
# git is for Hugo GitInfo field
RUN apk --no-cache add curl libstdc++ gcompat git

RUN curl -L -o hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v0.91.2/hugo_extended_0.91.2_Linux-64bit.tar.gz \
    && tar -xvf hugo.tar.gz hugo \
    && mv hugo /bin

WORKDIR /srv/app
