const formEl = document.getElementById("form") as HTMLElement;
const searchEl = document.getElementById("search") as HTMLInputElement;
const iconsEl = document.getElementById("icons") as HTMLElement;

const formPlaceholderEl = document.getElementById("form-placeholder");
formPlaceholderEl.style.height = `${formEl.offsetHeight}px`;

const keywords = [
    "blue musical notes pair eighth notes connected stems right-facing flags melody symbol floating harmony light blue dark blue edges vibrant artistic smooth edges musical notation melody",
    "green snake pixel character video game reptile side-view curling dark green light green open mouth fangs hostile small eyes iconic",
    "pixelated flower red yellow blossoms green leaves stem diagonal bouquet flora nature-inspired small simplistic sprite icon vibrant colors arrangement decorative",
    "Police officer, male, mustache, brown skin, black hair, blue hat, yellow badge, surprised expression, wide eyes, open mouth",
    "cow white gray black front-facing horns ears large eyes neutral expression four-legged standing simplistic cute",
    "lion pixel art yellow tan brown mane face front-view red tongue white eyes square calm whiskers ears simple",
    "chicken white red yellow beak comb wattle standing two legs side view tail wing animal",
    "pixel face brown hair small eyes white teeth smile joy male front-facing simple minimalist 8-bit low-res caricature digital square light-brown",
    "orange musical note black accents diagonal floating eighth note simplicity isolated singular",
    "hat beige purple ribbon white orange circular frontal simplistic accessory fashionable",
    "blonde princess pink dress gold crown wand yellow stars smiling frontal view fair skin happy short hair",
    "golden star-shaped small points glowing four-sparkles centered simple warm amber edges symmetrical two-dimensional bright cheerful iconographic floating smooth radiant decorative",
    "orange hair brown skin white teeth smiling square face black eyes male joyful expression front view",
    "drum cup blue red stripes yellow handle two beverage implied square rim front-view simplistic container small filled level tabletop resting sturdy",
    "brown square face smiling red lips white eyes black pupils simple frontal view minimalist character happy neutral expression",
    "small house red roof white siding gray chimney blue windows brown door simplistic two-story symmetrical front-view welcoming",
    "brown white red mushroom small cap dots two-eyed facing left character simple iconic video game super mario",
    "ear, human, side-view, brown, small, detailed, recognizable, body part, hearing, anatomy",
    "character brown hair red cap blue-striped white tank red shorts frontal view neutral expression standing brown shoes small",
    "snowman top-hat red scarf smiling carrot nose coal eyes buttons brown sticks arms white upright cheerful winter-themed accessory festive",
    "red black ladybug insect two antennae six legs symmetrical spotted round simple small overhead view",
    "hand pointing rightward brown simplistic index finger extended thumb visible fingers curled gesture indication directional communication skin-toned small digital representation clear icon",
    "green black wheels pixel-like resemblance to motorcycle side-view simplistic representation angular design small-scale stationary two-wheeled no rider abstract blocky minimalistic detail grayscale tires dark backdrop contrast transportation motionless",
    "orange square face blue tears crying sad expression front-facing minimalistic small mouth simple shocked emotional human-like digital",
    "train steam locomotive red gray wheels side-view chimney orange flame blue window black motionless compact simplistic horizontal orientation stationary classic design",
    "cow black white pink standing profile tail upright four-legged spots simple small ears two facing-left animal",
    "green dinosaur walking tail upright yellow small arms happy smiling two-legged playful",
    "soccer ball black white pentagons hexagons geometric spherical sports equipment symmetrical traditional design",
    "red heart purple wings flying yellow sparkles love vibrant emotion symbol passion caring health life glowing fluttering",
    "lion pixelated standing right-facing shades yellow tan brown tail four-legged small ears mane simplistic animal",
    "globe blue green spherical continents oceans simple iconic representation earth geography global environmental international worldly circular floating concept symbol planet",
    "white cat blue eyes pink nose small ears front view sitting whiskers curved tail alert",
    "blue knight red shield sword helmet visor facing left floating white handle strap grey blade aggressive stance",
    "character cartoon male black yellow pink frontal serious hat sunglasses stubble grey suit tie small ears collar shoulders white",
    "sushi maguro nigiri red white green orange black border rectangular rice fish topping seaweed band side view japanese cuisine",
    "penguin grey white orange black standing side-view small cute beak flippers feet looking forward calm",
    "female blonde blue dress white collar brown shoes smiling front-facing yellow hair bow short hair fair skin",
    "banana peeled yellow white brown tip green stem left-leaning angled fruit curved ripe floating",
    "baseball white red stitching spherical seams sports equipment symmetrical leather hardball recreation traditional professional hobby",
    "red sock yellow toe angled left-foot floating warm-tone orange heel simplistic dark-shadow clothing foot-garment",
    "red car side-view simplistic small wheels gray headlights yellow windows blue compact toy-like",
    "yellow helicopter blue windows side view small rotors landing gear compact simplistic silhouette rotor mast tail fin skids",
    "mask red devil horns yellow eyes fangs menacing black square shape centered frontal view",
    "shell pixelated egg shades white gray black diagonal speckled pattern oval simplistic icon small angled representation symbol easter item object",
    "shell egg-shaped blue white gradient shiny highlighted shadowed ovular smooth curved two-toned reflective diagonal orientation floating",
    "leaves brown lungs human organ anatomy health medical pair respiratory bronchi lobes trachea symmetrical vital body airways",
    "red creature two-legged simplistic eyes menacing claws orange antennae front-view symmetrical curved legs floating",
    "rocket ship blue red yellow flame ascending diagonal orientation pointed tip fins propulsion space exploration travel vehicle motion adventure launch dynamic exploration combustion upward speed",
    "wizard's hat pointed brim shades of gray simple iconic centered floating magical costume accessory traditional felt-like.texture",
    "blue fish swimming rightward two-fins tail round-eye open-mouth surprised-expression gills small aquatic side-view",
    "flame orange yellow red dynamic glowing warmth combustion flickering energy light heat burning fiery luminous vibrant intense isolated element bright",
    "blue white pixelated item tool diagonal sharp handle point minecraft sword videogame weapon iconic adventure combat crafting blocky sturdy cool-toned",
    "dark blue torch flame orange yellow light handle brown glowing handheld upright illuminating nighttime warmth adventure guidance safety exploration burning",
    "white flower orange center green stem leaves simplistic symmetrical upright bloom flora small",
    "ice cream scoop pink brown white blue bowl dessert three flavors sweet cold indulgent treat creamy confection refreshing dairy",
    "blonde blue eyes smile crown front-facing red lips fair skin square earrings yellow headband neutral expression light eyebrows",
    "red-headed open-mouthed surprised expression wide eyes brown eyebrows front-facing light skin white teeth simplistic",
    "moon cratered round grey white celestial orbiting natural satellite surface variations shadowed light dark spherical cosmic tranquil astronomical silvery cold",
    "monkey brown beige face frontal smile white teeth large ears happy simple hair dark brown eyes cheerful",
    "yellow orange school bus cartoon wheels black windows side view red stripe simplistic design transportation horizontal orientation",
    "blonde blue-eyed neutral-expression facing-forward fair-skinned male short-hair eyebrows-visible nose mouth-closed ears-none-visible square-jaw",
    "purple creature white eye small simple segmented blocky upright playful curved looking left tail whimsical two-dimensional lavender shaded single character",
    "jack-o'-lantern orange green black smiling carved triangular eyes nose glowing halloween festive front view",
    "female brown hair purple shirt neutral expression facing forward black eyes small mouth pale skin simplistic",
    "tan brown dog simple four-legged small tail ears pixel representation side view neutral expression stationary minimalistic blocky",
    "gray mouse pink ears front view cute small eyes whiskers upright centered simple light gray dark gray tiny feet little nose",
    "pizza triangular yellow red brown crust pepperoni cheese melted toppings italian food slice delicious savory snack meal dine warm appetizing",
    "blue wave water tide",
    "gray rabbit pink ears white tail side view sitting small black eyes calm whiskers four-legged fluffy",
    "space-invader purple alien game character pixeled antenna two-legs claws arcade retro enemy",
    "radio antenna dark gray light gray dials knobs speaker square portable handle old-fashioned",
    "red balloon floating string small brown handle round helium festive bright lightweight buoyant simplistic celebration object unaccompanied airborne upward shiny",
    "blue white gray water boat waves small floating simplistic side-view tranquil still single miniature",
    "toast beige crust brown sliced bread square top-view flat one-piece simple edible carbohydrate breakfast toasted light shadow corner staple-food",
    "orange yellow bolt diagonal sharp electric dynamic symbol energy vibrant jagged power striking flash charged",
    "green dinosaur small pixelated simplistic cute four-legged tail standing side-view light-green dark-green white eye happy",
    "elephant blue minimalistic cute small trunk ears four-legged tail standing facing-left simple calm",
    "chicken white red comb yellow beak feet standing profile small tail feathers plump domesticated farm animal avian side-view",
    "brown book front cover closed white rectangle label",
    "carrot orange green diagonal left-leaning white spots brown tip roots tapered vegetable",
    "bowling ball black three holes two pins white red stripes upright round heavy recreational sport indoor spare leisure strike potential glossy",
    "green cylinder two white vertical stripes reflective highlights simplistic icon symbol circular top flat bottom",
    "trophy gold cup handles black base reflective shiny achievement award victory success celebration front-facing symmetrical",
    "red mushroom white spots game item health vibrant glossy healing iconic overhead view red dots simple bright contrast two-dimensional",
    "green frog square frontal simple eyes large white black pupils staring mouth small nostrils two light-green dark-green borders symmetric expressionless",
    "computer monitor flat screen dark blue light grey black stand front view minimalist design small bezels blank screen reflective surface",
    "green recycle symbol three arrows circular motion white circle dark background environmental conservation symbol sustainability",
    "black yellow gray small floating mechanical insect-like wings antenna centered symmetrical overhead view abstract simple robotic hexagonal body two-toned wings",
    "castle blue gray symmetrical towers battlements central doorway fortified rectangular windows arch simplistic small iconic sturdy medieval stone-like protective structure",
    "red bird small beak yellow standing profile left-facing two-legged tail cute simplistic wings orange feet",
    "blue dolphin small simplistic abstract rightward aquatic mammal fin tail intelligent marine graceful curved happy minimalist",
    "brown bear face front-view simple black eyes nose red mouth friendly symmetrical two-toned ears neutral-expression",
    "purple octopus cartoon two eyes tentacles facing front simple cute small flat design symmetrical smiling underwater creature iconic cheerful",
    "green lime square brown spotted tiny legs creature simple cartoonish smile cheerful minimalistic sideways four standing tail cute light-green antennae",
    "purple shirt short sleeves collar button-up casual front view simple design lavender clothing small shadows garment",
    "music notes purple black eighth note beamed quaver isolated hovering melody symbol pair musical notation sound rhythm",
    "blue musical note eighth note dark light blue outline shadow effect floating simplistic icon silent symbol auditory melody single",
    "bone white geometric symmetrical four-pointed cross-like simplified abstract central icon balanced emblematic stark contrast minimalistic",
    "star orange shadow brown white curve tail simple celestial glowing edges centered corner shading points small accentuated",
    "female brown hair smiling red lipstick purple shirt white skin facing forward wide eyes long hair simple small earrings",
    "yellow smiling face round two eyes black simple large mouth teeth four white happy expressive flat frontal view",
    "yellow circle two squares black-dot eyes line smile pink outstretched tongue happy playful simple front-facing whimsical iconic cheerful digital emoticon",
    "yellow surprised face open-mouth wide-eyed circular brown eyebrows raised simple abstract emotion expression shock two-dot eyes dark squares central feature",
    "crescent moon white gray shades curved waning celestial night astronomical",
    "family trio smiling front-facing brown hair black hair blue top purple top red top light skin dark skin neutral expression",
    "elderly woman gray hair red lips wide eyes surprised expression pink cheeks white earrings frontal view concerned",
    "male brown hair mustache serious expression frontal view beige skin black eyes eyebrows neutral mouth",
    "green purple masks smiling frowning floating square eyes contrast dual emotions simple pair facial expressions",
    "apple red green brown stem leaf fruit ripe shiny round fresh",
    "5 beige hand five-finger front-facing palm centered thumb index middle ring pinky fingers shadowed-right-side flat gesture clear simple small square-shaped neutral",
    "sphere green blue white clouds continents ocean round small simulated earth planet geography global floating space concept eco-friendly representation concept environmental",
    "corn cob yellow kernels green husk left-leaning ripe food agricultural produce partial unshucked organic natural healthy vegetarian ingredient maize vibrant",
    "blue potion bottle white liquid container cork shiny reflection gradient light source upper left small gray shadow",
    "red bow pixelated-art ribbon gift simple symmetrical two loops central knot shadowed bottom tails decorative festive",
    "palette circular beige green blue red yellow squares abstract simplistic centered geometric brown edges colorful quadrants muted tones",
    "orange guitar brown fretboard strings musical instrument small white tuning pegs diagonal right-leaning curved body",
    "equalizer bars gray white vertical gradient varying heights four sound adjustment control interface",
    "red square lamp grey pole orange windows minimalist small dark lighted structure standalone",
    "snowflake blue light blue symmetrical six-pointed geometric centered frozen crystal delicate intricate winter icon cold flake seasonal decorative nature-inspired radial festive",
    "blue anchor navy marine symmetrical flukes shank crown stockless nautical maritime bold simple icon emblematic seafaring heavy-duty secure stability symbol",
    "pixelated mushroom super mario red white brown spotted cap stem iconic video game item power-up small simple floating inedible",
    "fist raised orange beige yellow lines palm clenched thumb visible fingers curling knuckles compact solidarity gesture strength unity symbol",
    "guitar orange brown musical instrument strings fretboard headstock tuning pegs bridge white sound hole acoustic diagonal orientation",
    "house two-story yellow brown door blue windows green tree brown trunk front view small simple design",
    "tree green brown pixel simplistic blue blocky miniature isolated digital nature-themed vibrant water trunk foliage calm serene floating tiny representation",
    "lemon yellow green leaf fruit round citrus two-tone food ripe",
    "brown skin black hair wide eyes white shirt yellow collar neutral expression front view male small ears short hair",
    "orange round green leaf stem fruit ripe small shadow curved simple bright smooth fresh floating",
    "character green top brown boots yellow scarf floating relaxed arms crossed serene blue surface ledge sitting casual side-view simple clear",
    "sailboat orange white blue small simple floating calm centered water vessel horizontal marine leisure tranquil minimalistic serene nautical reflection sunset",
    "building miniature red brown windows gray rectangular doors white simplistic structure frontal view symmetrical two-story roof chimney",
    "smiling sunglasses yellow black cool confident positive square simplistic minimalist emoticon facial representation icon digital cheerful face accessory opaque headwear",
    "red telephone three white buttons corded handset horizontal orientation communication vintage rectangular base curved receiver",
    "red brown container simplistic flat two-dimensional upside-down hanging abstract vessel empty smooth curved edges open top suspended bright",
    "green tractor yellow wheel small front-loader gray exhaust pipe black tire simplistic design agricultural machinery side-view cabin window front headlights",
    "gray vertical traffic light red yellow green plus signs symbol orderly control device street regulation safety signals illuminated traffic management urban",
    "tree green brown trunk leaves rounded simple nature upright stationary symbolic foliage symmetrical botanical organic growth",
    "umbrella purple magenta blue white stars handle j-shaped accessory protection curved portable sparkling celestial overhead",
    "yellow smiley face digital emoji square simple happy teeth showing black eyes mouth frontal view cheerful",
    "ambulance white red stripe cross blue window wheels gray tires side view emergency vehicle healthcare transport urgent",
    "yellow blush smiling round happy pink cheeks simple minimalist black eyes small mouth joyful front-facing",
    "smiling sun orange yellow warm happy round bright friendly cheerful glowing simplistic front-facing radiant icon positive small facial features luminous",
    "chocolate cake blue candles white plate brown lit celebration dessert icing three flames small birthday",
    "5 star golden five-pointed symmetrical centered flat simple iconic bold warm",
    "envelope white gray shades closed flap rectangular communication icon message correspondence mail symbol digital opening light dark",
    "truck red yellow grey blue small wheels blocky side-view simplistic cargo area cab rectangular shapes tiny windows interactive toy classic design",
    "dancer red dress brown hair raised arms spinning motion female joyful movement dynamic pose elegant brunette lively twirl flowy silhouette",
    "alien gray white black large eyes small mouth head extraterrestrial front-facing mysterious iconic simple emotionless minimalistic fictional character silhouette",
    "elderly gray-haired white balding male smiling brown-eyes front-view simplistic ears eyebrows minimalistic warm approachable content serene neutral-tone clear digital representation",
    "christmas tree green red yellow gold star ornaments festive celebration vertical small brown trunk symmetrical tiers",
    "gift red yellow ribbon bow square wrapped present celebration box two-tone festive",
    "blue orange diagonal conical metallic rocket propulsion flame motion small space exploration shiny technology combustion travel exploration speed power futuristic",
    "lollipop red orange yellow swirl round candy brown stick sweet treat confectionery dessert spiral glossy small handheld",
    "cherries two red green stem attached shiny ripe fresh fruit pair dangling sweet small shadowed vibrant juicy edible natural wholesome",
    "shamrock green three-leaves symmetrical irish lucky charm st. patrick's day emblem small stem centered plant simple",
    "red white santa hat pompom diagonal festive headwear fluffy rim holiday christmas warm cheerful accessory traditional costume seasonal felt headpiece",
    "round beige red-and-white mushroom spotted cap stem small simplistic icon food-related fungi natural flat unshaded circular",
    "santa claus red white beard hat cheerful front-facing glasses round face moustache festive fluffy trim belt buckle jolly iconic holiday character fictional",
    "glasses green lime neon rectangular white lenses opaque horizontal blocky simplified eyewear accessory two-dimensional contrast bright dark edges fashion",
    "pineapple yellow green brown fruit tropical spiky crown oval textured",
    "strawberry red green seeds fruit ripe sweet juicy fresh vibrant natural delicious edible healthy organic small refreshing summer",
    "watermelon slice red green black seeds juicy ripe triangular fruit summer refreshing sweet bitten missing piece white rind",
    "bell gold red bows front-view shiny curved clapper hanging two symmetrical decorative ringing small top-view round polished metallic",
    "christmas tree red green yellow gifts brown festive cheerful ornaments colorful presents holiday celebration decorated star top square rectangles",
    "white candle red flame yellow bright green holly berries brown base wax melting lit warm glowing festive christmas decoration seasonal vertical",
    "spinning top red yellow green toy symmetrical vibrant spinning small contrasting playful festive traditional motion blur central simple compact bright",
    "gift red gold ribbon bow box wrapped shiny celebration festive surprise present square bright two handles",
    "red yellow spinning top diagonal stripes pink tip small toy simple glossy shadowed right side circular body",
    "snowman white orange yellow green red brown front-view smiling scarf top-hat carrot-nose standing branches-arms coal-eyes",
    "green red plant diagonal flora stem leaf vibrant nature pixel item small icon minecraft game berry",
    "candy cane red white striped hooked sweet festive diagonal traditional christmas confection treat bent glossy hard candy",
    "red green yellow horizontal stripes white small bright circular central symmetrical spinning vibrant top capped festive decorative floating",
    "broom brown gray pink dust particles cleaning wooden handle upright sweeping motion two-tone bristles floor maintenance",
    "red gold zigzag upward ascending chart positive growth diagonal increase trend squares blocks simple abstract finance arrow bullish",
    "yellow animated guitar brown neck smiling side view musical instrument strumming character simple minimalistic cheerful anthropomorphic playful entertainment melody performance small bright",
    "blue sapphire circular small gemstone faceted reflective shiny centered jewel precious cobalt lapis azure translucent",
    "low-resolution circular brown beige orange white dark blurred abstract ambiguous warm-tones centered round-form pixel-like mosaic gradient simplicity geometric contrast spherical",
    "blue orb swirling pattern spherical gradient central lighter edges darker simplistic smooth abstract circular centered tranquil uniform radiating azure cobalt",
    "red brown orange circular shape marbled pattern shading bright warm colors abstract sphere-like smooth texture gradient centered floating reflective appearance terracotta tones rust-colored glossy illuminated muted contrast",
    "earth globe blue green brown spherical geography continents oceans miniature representation planet horizontal terrestrial environmental ecology global floating space concept",
    "sphere gray white black circular shaded contrast 3d moon-like celestial small smooth spherical floating isolated",
    "stork white orange brown standing profile two-legged beak small eye feathered texture wing tail simplistic digital drawing",
    "cheese wedge yellow orange holes shadowed bottom right gradient brown spots triangular ascending left",
    "pixelated ice cream cone diagonal brown white gray dessert two-scoop handheld summer treat frozen sweet waffle cone creamy indulgence refreshing classic snack vanilla chocolate",
    "red vertical bar yellow orange green blue pattern gradient horizontal small square purple aligned minimal bright column rose crimson lavender",
    "red hat blue eyes neutral expression brown hair pointy white skin male frontal view serious small ears unsmiling iconic character",
    "green square happy apple red stem white shine black eyes simple cute two leaves smiling blushing cheeks front-facing",
    "yellow bee blue eyes black stripes wings flying two antennae side view cute small buzzing insect",
    "red black blue grey yellow white blocky windows fire escape structure urban facade rectangular shapes dark rooftop",
    "red butterfly symmetrical yellow spots blue accents central body antennae two wings simple iconic floating small insect",
    "taxi yellow blue checkered red top light white side wheels magenta platform stationary small windows front-facing compact transportation",
    "green zombie red pot pixel art smiling cartoon arms raised cute undead small ears yellow details simplistic two teeth front view",
    "red car four wheels black tires side view yellow headlights three windows small simplistic square body stationary",
    "blue cat yellow eyes red collar tail up four legs standing small ears facing right whiskers",
    "christmas tree yellow star red blue green ornaments gifts purple pink yellow festive upright small centered celebratory seasonal traditional",
    "pink angry eyes red white frowning floating blue lightning bolt simplistic two-dimensional character square expression aggressive",
    "green dinosaur pixelated red stripes yellow standing tail long neck small arms white claws two legs upright simplistic",
    "green yellow red collar standing four-legged tail ears simplistic small blocky creature domesticated animal friendly",
    "globe blue green simplistic digital continents oceans spherical representation earth geography global round icon emblematic miniature ecological environmental concept",
    "flower yellow red pot green stem leaves brown soil simple bright centered small blooming cheerful single upright",
    "red guitar vertical yellow purple stripes neck frets brown headstock simplistic icon music instrument six-string solid-color",
    "blue zombie pixel character red eyes cyan mouth square head simplistic emotionless green ears frontal view undead digital icon representation",
    "red heart small white highlight love symbol affection health emotion vibrant floating centered simple iconic positive sentiment passion",
    "red heart happy eyes smiling white simple centered two-dimensional cute friendly emotive charming affable welcoming radiating warmth love joy graphic",
    "helicopter pink yellow orange green skids tail boom cockpit side view simplistic rotor blades airborne small vehicle",
    "red blue green zigzag lightning bolt-shaped diagonal orientation bright contrasting simple iconic symbol electric sharp edges dynamic energetic",
    "red house chimney blue roof purple facade yellow windows green lawn simplistic two-story rectangle square front-view structure",
    "pink yellow ice cream cone character cartoon smiling two eyes red cheeks floating cute simple design happy expression",
    "yellow cat monster horns purple smiling teeth red tongue green leaf cheerful face-front big-eyes playful",
    "yellow blue green truck side-view four-wheels minimalistic two-tone cargo tiny pink rectangle simple motionless blocky toy-like",
    "music note blue symmetrical melody icon sharp edges clef rest upbeat audio tune harmony pitch flat rhythm symbol sound",
    "pencil blue light-blue yellow pink purple gray diagonal upper-left to lower-right writing utensil sharp graphite eraser wood drawing hexagonal",
    "gift box red green yellow stripes bow square wrapped present festive celebration top-view ribbon two-loop container bright cheerful packaging surprise",
    "rainbow red orange yellow green blue purple arch simplified small centered flat vibrant semi-circular graphic icon colorful",
    "red yellow animal four-legged tail horns spots stylized simplistic fictional small ears standing profile view playful",
    "butterfly symmetrical red blue green yellow pixel squares centered abstract simple wings antenna four-legged small minimalist geometric vibrant insect",
    "blue snowflake geometric symmetrical six-pointed centered abstract simple structured cold-themed intricate sharp edges delicate wintery",
    "snowman white red top-hat green yellow scarf black buttons orange carrot nose coal eyes mouth cheerful centered blue square simple",
    "smiling yellow round black-bordered eight-pointed happy red-mouthed simplistic bright centered positive cheerful friendly welcoming circular graphic icon two-eyed",
    "red umbrella yellow handle blue tip floating upside-down cheerful simplistic curve protection portable sunny object accessory bright inverted shelter handheld",
    "fox orange brown square frontal view yellow simple small ears nose two-tone animal whiskers looking forward happy",
    "white rabbit pixel illustration pink ears cute blue eyes small nose front-facing simplistic two whiskers blushing cheeks neutral mouth upright",
    "pixelated round face pink confetti happy blush eyes red mouth open cube-shaped celebration front-view floating cartoon",
    "elephant blue pink ears trunk down small eyes two tusks four-legged simple cute standing square canvas",
    "white ghost cute smiling black eyes pink cheeks floating two-dimensional minimalist round corners small simple friendly playful positive character iconic recognizable",
    "red white dots mushroom smiling cute two eyes small tiny vertical simple happy friendly iconic video-game character fungi",
    "robot gray yellow antenna square-head happy small-ears centered simplistic red-light friendly front-facing",
    "yellow rubber duck orange beak sideways floating small simple cute toy iconic bath time cheerful light smooth edges",
    "unicorn white multicolored horn mane pink green yellow blue cookie brown cartoon side-view happy standing mythical creature animal fantasy smiling",
    "cassette blue yellow white black rectangles circles front-view neutral-expression two-eyed small-mouth anthropomorphic stationary horizontal compact nostalgic music-storage",
    "pink blue white black cassette tape cute music media storage retro object horizontal small simple smiling anthropomorphic",
    "red cassette tape smiling white reels black squares for eyes horizontal orientation teeth anthropomorphic happy music storage retro",
    "tan green white red square cassette horizontal stripes eyes brown happy simplistic antique music storage nostalgia facial features object retro technology",
    "fire emoji flame yellow orange red cute small smiling eyes simple warm happy cartoon bright friendly expressive",
    "goldfish orange white eye fins tail side-view swimming simple aquatic animal small peaceful",
    "blue pixel character smiling octopus orange tentacles front-facing white eyes small happy aquatic curved underwater creature",
    "pink green red flower ears eyes pot blooming standing happy small plant two leaves",
    "yellow snail smiling antenna red shell circular pattern side-view rosy cheeks cute happy small eyes open mouth friendly",
    "green dinosaur standing side-view smiling white dots red mouth yellow eyes four-legged tail small arms",
    "watermelon character red green white standing smiling teeth black eyes anthropomorphic happy fruit two-legged seed-pattern arms-hidden",
    "flower yellow orange green smiling frontal potted red brown cheerful stationary simplistic bright happy two-leaves",
    "diamond blue light-blue cross gold brown handle floating glimmering kite-shaped suspended sparkling gemstone ornate jewel reflection treasure luminous icon radiant",
    "pumpkin pie orange yellow brown crust whipped cream white dollop dessert steam hot front view round thanksgiving festive",
    "fried egg sunny-side up yellow yolk white orange speckles two egg whites disjointed simplistic food breakfast glossy yolk center",
    "transparent square modern handle minimalistic beverage gray white simplicity glass container right-facing flat liquid filled partial tabletop object beverage-holder reflective",
    "orange yellow brown pixelated pot gold bright shiny container full wealth treasure riches curved handles metallic horizontal overflowing",
    "white gray red uppercase 'e' beveled handle left side cup reflective blocky ceramic-looking simple bold",
    "metal spoon cooking utensil long handle angled right diagonal kitchen tool stirring scoop simple functional serving food curved traditional",
    "wooden spoon cooking utensil brown long handle angled right diagonal kitchen tool stirring scoop simple functional serving food curved traditional",
    "three platforms floating horizontal yellow red green blue blocks staggered varying sizes",
    "abstract multicolored squares dispersion floating red blue yellow green disintegration central downward dynamic random geometric patterned scattered playful",
    "drill red black gray corded handheld tool power trigger chuck electric construction rotating hardware diy maintenance repair",
    "pixelated white shower head silver nozzle orange brown bucket filled water four-legged stand black outline shadow square base side-view simplistic",
    "bars graph red yellow green tall short ascending multicolored purple data visualization simple flat design progression",
    "default multi color cross plus dotted dashed square white outline",
    "candles red blue yellow flame celebration cake white frosting brown base dessert food birthday lit colorful arranged orderly glowing festive",
    "birthday cake candles red blue yellow flames white orange icing layers chocolate festive celebration lit dessert rectangular sweet brown beige confectionery",
    "golden coins three stacked shiny floating currency treasure wealth circular edges collectible identical economic icon abundance game asset riches overhead view monetary",
    "chocolate bar squares brown tan dark light segmented confectionery dessert cocoa sweet treat rectangular snack indulgence creamy tiled edible patterned",
    "red white blue square abstract patterned symmetrical centered geometric contrasting bordered bold checkered",
    "gradient gray white staircase ascending right shaded steps corner angular solid small floating",
    "gold ingot yellow shiny metallic rectangular diagonal gradient reflection shadow solid wealth currency investment resource precious heavy stackable valuable bullion",
    "cupcake white frosting yellow cup small dessert sweet treat bakery icing swirl simple delightful edible snack baked creamy topping confectionery",
    "popcorn white red striped bowl snack fluffy salted overflow heap clustered food tasty cinema iconic treat crunchy indulgence appetizing",
    "spoon gray silver metallic small simple diagonal utensil eating tool curved handle scoop shiny reflective isolated",
    "5 number five bold blue white red shadow lowercase slanted blocky gradient central solid",
    "mathematical symbols green apple red bird blue equals sign addition subtraction multiplications division simple icons yellow beak stem leaf brown",
    "cheese yellow holes brown chocolate square wrapper red partial unwrapped cube snack food contrast sweet savory",
    "pencil icon diagonal yellow orange graphite eraser pink point white gray writing drawing sharp creative tool wooden office school stationery",
    "yellow green red orange blue purple vertical aligned repetitive laughter letters capitalized two-rows joviality text square-shaped bold multicolored grid-layout simplicity",
    "red question mark center orange dots green floating symbol dark mystery inquiry punctuation curiosity vibrant contrast digital",
    "pixelated orange red yellow blue green purple speaker sound waves question mark floating vibrant abstract geometric small right-facing gradient blocky simplistic",
    "blue round face simplistic two dots eyes curved smile pink cheek highlights happy expression centered",
    "yellow taxi top-view red cat side-view brown stripes green plus sign floating black wheels tail upright simplistic small",
    "blue question mark yellow punctuation dots leaning curious mystery symbol icon information inquiry ask communication question",
    "white red punctuation exclamation mark symbol alert attention vertical minimalistic two-tone emphasis graphic bold isolated communication concept sign",
    "speech balloon white red exclamation mark outlined black dialogue bubble alert punctuation emphasis communication icon urgency",
    "magnifying glass cyan brown handle three black dots expressionless round simplistic design centered neutral sentiment small shadow",
    "calculator orange grey buttons display mathematics compact handheld digital device calculating tool modern finance numbers screen electronics portable",
    "1 number one yellow bold serif font large dark background top-left alignment",
    "2 blue number two digit bold dark background right-leaning bright blocky silhouette central large simple flat",
    "3 orange number three bold large central black outline shadow flat bright contrast single digit serif",
    "green number 4 diagonal simple bold dark background mathematical digital gradient large centered abstract geometric",
    "pink number 5 digital magenta minimalist bold flat centered large modern geometric square border",
    "6 red number six bold centered dark background digital angular edges serif font flat symmetrical simple large prominent",
    "orange number seven 7",
    "8 green number eight dark squares contrasting bold symmetrical centered digit large geometric two holes simple flat monochrome",
    "9 blue number nine digit bold serif font upright solid gradient top-shadow glossy beveled edge dark outline two-toned",
    "golden bold number 10 blocky digital centered",
    "11 number eleven blue vertical bold dark background large numeral two digits top-view",
    "12 red black digital number twelve vertical bold flat-design isolated contrast bright large centered clear numeral",
    "13 green number thirteen bold large front-facing digit square isolated",
    "number 14 pink magenta bold large top-left orientation black background flat digits digital clock-style numerals",
    "red number 15 bold large centered digital display",
    "16 gold number sixteen large bold uppercase blocky orange outline flat centered digital display contrasting dark",
    "green digits 17 large bold angled gradient dark-light top-left to bottom-right orientation flat number two-tone contrast",
    "blue number 18 bold digital large centered dark blue outline square shape",
    "yellow black number 19 bold digital square corner-rounded",
    "blue number twenty 20",
    "red number twenty one 21",
    "green lime number 22 bold blocky large centered digital bright contrasting dark background flat two-digit",
    "23 two-digit white magenta bold large blocky flat centered even-spacing square-corners",
    "24 red black white number twenty-four bold digit two four",
    "numbers gold bold 25 centered flat large square contrasting black background",
    "green white large 26 bold flat numbers digital two-digit square central symmetric adjacent numerals",
    "blue white number 27 large centered bold contrasting simple iconic sports jersey indicative team digit",
    "gold black numbers 28 blocky digital bold centered contrasting",
    "blue digits number 29 large bold contrasting centered two nine blocky digital flat dark-background simple clear two-digit square-layout graphical integer",
    "red black numbers 30 bold contrasting digital large centered graphic vivid flat two-digit icon square-shaped dynamic sports-related simplicity clarity impactful",
    "book blue yellow smiling anthropomorphic front-facing pages standing arms happy character",
    "blue flower face happy green stem red pot two-leaves front-facing smiling simplistic",
    "green yellow white crown angry fangs animated character frontal view pink cheeks black eyes square shape",
    "green book smiling red bookmark happy anthropomorphic front-facing upright simplistic two-legged",
    "diamond blue light blue white geometric shiny faceted symmetrical two-dimensional gemstone edges corners floating centered reflective gradient",
    "cupcake white pink cream cute small smiling face fluffy icing liner dessert baked sweet treat edible miniature cheerful friendly sugary",
    "monkey brown beige smiling ears front-facing simple symmetrical friendly black eyes eyebrows nostrils small mouth head-only",
    "panda black white pixel art square front view neutral expression digital simple symmetric animal ears eyes nose mouth",
    "white unicorn pixel beige gold horn wings mythical creature standing side-view tail mane brown hooves grey small ears simple elegance",
    "pink book smiling white pages yellow bookmark happy front-view anthropomorphic simple face two eyes black mouth",
    "animated character red square eyes happy expression white stripe blue necktie blocky simple standing frontal view",
    "red flower pixelated green stem brown pot happy face two leaves smiling front-view blooming terracotta-colored",
    "red strawberry green leaves digital fruit smiling face eyes black seeds cute anthropomorphic happy cartoon",
    "yellow square smiling eyes black simple brown book green binding happy anthropomorphic character front-view standing upright pages two-dimensional",
    "alarm clock orange white black numbers hands timepiece three-dimensional perspective blocky simplistic round interface ticking eleven fifty-five indicating hours minutes classic design tabletop",
    "red gold shovel hat white stripe vertical handle brim festive standing santa christmas tool digging seasonal square-shaped holiday illustration small",
    "scarecrow red hat blue shirt brown pants tan face standing green patch yellow straw arms outstretched friendly small dark-background",
    "pumpkin orange green stem carved face eyes triangle-shaped nose mouth jagged toothy grin halloween front-view festive celebration autumn",
    "blue bird flying wings orange beak feet small shadow diagonally upward left cute",
    "two birds blue orange beaks facing left floating simplistic identical paired small dark background",
    "red apples three cluster brown stems green leaves shadowed highlight glossy ripe fresh fruit arrangement",
    "blue orange yellow purple white green pink magenta squares grid arranged colorful six-by-four",
    "light blue snowflake symmetrical geometric hexagonal winter cold crystal intricate delicate frozen nature-inspired seasonal ice decorative",
    "blue face pixelated smiling simple round eyes pink cheeks happy minimalist small digital avatar character abstract representation emotion friendly inviting",
    "red brown green blue abstract simplistic vertical bright warm square vibrant gradient blocky contrasting bold rectangular small two-dimensional flat minimalist",
    "crown purple gold orange yellow red white checkered circular gemstones front-facing symmetrical majestic ornate royal",
    "pigs wolf pink grey frontal view clustered four simple ears snouts eyes characters fairy tale three one group",
    "pig pink brown four-legged tail side-view small ears simplistic snout standing",
    "brown orange glowing spherical shaded textured patterned round warm illuminated abstract smooth gradient amber fiery floating reflective golden radiant ember-like",
    "blue sphere light circular gradient shadow centered round glowing reflective orb small floating translucent smooth mysterious",
    "planet rings saturn-like tan brown beige white small celestial orbiting space isolated spherical diagonal orientation iconic simple",
    "red white black guitar diagonal musical instrument strings body neck headstock frets pickups bridge tuning knobs right-handed solid-body",
    "crescent moon yellow dark night celestial glowing curved left-facing simple small stars scattered twinkling ambient small warm",
    "red white diagonally-oriented pixel-art wand magic fantasy silver gray simplicity accessory game item casting tool sparkles",
    "teddy bear brown orange white black red bowtie seated front-facing symmetrical cheerful stuffed animal",
    "orange acoustic guitar brown fretboard strings six headstock tuners sound hole musical instrument diagonal orientation simple minimalist icon",
    "blue spider eight-legged simplistic symmetrical centered light-blue dark-blue shades creature digital icon small legs body arachnid",
    "blue flower light blue petals central yellow orange bloom small symmetrical vibrant flora eight-petaled centered",
    "yellow brown claw animal quadruped standing red eyes simple abstract small ears tail side-view stationary four-legged creature",
    "bone tan cream minimalistic icon symmetrical horizontal two-dimensional canine simple abstract neutral representation object centered graphic",
    "yellow red circular two protrusions centered abstract simple round bottom geometric symmetrical minimalist icon small bright contrast",
    "brown faces triangular ears square snout tan interior ear black eyes nose simplistic three identical symmetrical neutral expression",
    "yellow green pink stars sparkling small clustered bright centers fading edges scattered decorative festive celestial vibrant glowing three separate magical simplified",
    "green alien black eyes face head extraterrestrial simplified front-facing emotionless small ears dark ominous mysterious minimalistic humanoid",
    "bee yellow black white stripes wings flying insect small antennae six legs two eyes facing upwards symmetrical",
    "bird blue yellow white red perching side-view plump small beak tail calm two legs standing",
    "red yellow blue symmetrical butterfly insect two wings four sections antennas small centered simple vibrant",
    "camel yellow tan brown quadruped silhouette standing side view calm simple minimalistic hump tail neck four legs animal",
    "cat orange brown standing front-facing yellow eyes alert tail up small ears four legs whiskers nose serene",
    "orange cat sitting yellow eyes tail upright ears small whiskers attentive cute front-facing brown accents shaded four-legged",
    "gray cat yellow eyes orange ears white spots front-facing tail raised small ears standing four-legged",
    "cat gray black yellow eyes red ears seated neutral expression front view tail whiskers small nose pointy",
    "green arch zigzag pixel blocky geometric symmetrical icon abstract bright gradient chartreuse lime dark edges curves simplistic digital",
    "animated character lion cub brown mane yellow face cute small sitting orange paws frontal view happy whiskers ears bright-eyed smiling",
    "chicken white red comb orange beak brown legs side view neutral expression two visible claws small tail standing",
    "chicken red yellow orange brown beak comb tail feet two-legged side-view simple small animal",
    "pixelated cow white black spots gray horns pink snout red collar yellow bell standing profile neutral expression four legs tail",
    "cow brown white small side view standing blue bell tan hooves tail upright ears serene",
    "crab orange black eight-legs two-claws centered simple small flat marine creature symmetrical",
    "orange brown cat standing blue scarf white stripes upright tail whiskers ears front-facing paws happy",
    "wolf pixel art gray black white yellow eye standing four-legged tail ears upright small digital",
    "green yellow orange animal four-legged small eyes glowing square shadows side-view tail walking simplistic creature",
    "dinosaur pixel green small standing profile red eye simplistic blocky quadruped tail dark green spots light green body",
    "animal lounging brown blue red white resting horizontal relaxed chair cushioned small indoors cozy domestic comfy serene",
    "dinosaur brown orange pixelated side-view standing tail legs small arms neck calm simple digital representation creature extinct prehistoric quadruped silhouette",
    "cat brown tan stripes small yellow-eyed standing profile-view tail four-legged ears simplistic",
    "dinosaur green red orange quadrupedal tail yellow small spikes walking prehistoric creature reptilian",
    "green dinosaur small smiling upright two-legged tiny arms tail yellow spots friendly cute simple",
    "green dinosaur pixel red stripes white eye tail standing profile small arms yellow belly two-legged friendly simple cute upright curved-neck",
    "white dog pixel standing blue collar red spot tail upright black dots legs small ears flat",
    "brown llama four-legged standing white facial features ears pink neutral expression simplistic cartoon small tail dark brown hooves",
    "gray white red dog pixel small ears tail four-legged side-view simple cute standing calm stationary light-gray dark-gray two-toned white-spot upright-ears",
    "dog brown tan white red collar standing side-view tail ears upright four-legged canine small simplistic friendly domesticated digital representation",
    "blue shark smiling white teeth fin happy aquatic animal marine facing left cartoon cute small eyes gray underbelly",
    "duck green head white body brown wing orange beak feet side-view standing calm",
    "pixelated dog gray white black standing side-view small tail ears paws minimalistic four-legged companion domestic",
    "blue elephant head facing forward small pink ears white tusks simple cute stylized cartoonish trunk curved two-dimensional frontal view symmetrical minimalistic friendly",
    "green frog yellow-eyes smiling frontal-view small simple bright amphibian friendly cartoon square-shape happy whimsical digital illustration character minimalistic cute nature-inspired",
    "white ghost two eyes black smiling floating simple cute friendly small rounded corners centered light-gray shadows symmetric happy character",
    "giraffe brown yellow tan standing profile long-neck four-legged small-tail ossicones simplistic",
    "mouse",
    "green frog smiling red headphones front-facing dark eyes standing two-legged open-mouthed joyful animated character arms outstretched small cute",
    "donkey gray white standing profile simplified blocky four-legged tail mane ears small dark-gray hooves gentle calm neutral-expression creature mammal equine",
    "brown horse standing quadruped four-legged tail mane darker muzzle hooves lighter underbelly small ears profile stylized",
    "brown horse standing small minimalist light mane dark legs tail facing left simple quadruped cream muzzle ears serene",
    "ladybug red black dots wings tiny insect six-legged antennae symmetry overhead view simple",
    "dog brown tan pixel creature standing four-legged ears upright tail wagging friendly small spots simple digital representation animal mammal domesticated",
    "lion standing brown tan mane dark brown tail four legs ears facing left mouth open black eyes whiskers",
    "dog brown tan black standing four-legged tail ears-upright friendly simple square-bodied straight-tail small-eyed open-mouthed tongue-visible dark-nose front-facing",
    "mammoth brown tusks white minimalistic facing-front symmetrical trunk curled ears large ivory prehistoric animal woolly extinct simple iconic representation mammal",
    "green white dinosaur pixel character small cute simplistic side-view standing tail two-legged smiling happy crest-headed light-green white-belly",
    "monkey brown beige blue-eyed side-view tail curious standing small digital illustrated simple cute animal ears two-toned creature",
    "monkey digital head orange white brown ears muzzle eyes small mouth neutral expression simple cute frontal view",
    "blue octopus smiling tentacles light-blue eyes white small mouth cute aquatic creature frontal-view symmetrical happy marine simple cartoon character friendly",
    "owl brown tan yellow beige front-facing large-eyes small-beak feathers standing round-shape two-toed claws alert nocturnal bird",
    "panda head front-facing black white ears eyes neutral-expression cute symmetrical nose whiskers pink inner-ears small",
    "parrot blue yellow orange perched side-view black eye white beak brown branch stationary green feathers vibrant tropical avian animal",
    "white unicorn gold horn wings mythical creature side-view standing tail hooves mane calm magical yellow accents",
    "penguin black white orange standing upright neutral-expression small chubby flippers beak feet compact cute simple character front-view solitary",
    "dinosaur brown blue red orange standing tail upright small arms two-legged playful prehistoric creature cartoon",
    "pig pink brown small standing side-view four-legged tail ears snout simplistic cute",
    "white elephant small pink ears tusks tail side-view four-legged standing gray shades cute minimalist trunk red eyes compact simple representation",
    "gray rabbit sitting profile pink ears white tail whiskers leftward small eyes calm fluffy compact four-legged animal cute soft side-view",
    "small gray quadruped simplified blocky horns ears tail white eyes frontal stance simple light shades four-legged minimalist representation creature",
    "bird perched brown red white beak side-view tail small feet simplistic two-dimensional sitting animal calm stationary",
    "robot gray yellow smiling square head small eyes antenna front-facing torso red button arms neutral position",
    "yellow duck side-view orange beak happy simplistic small two-dimensional floating cartoon graphic bright aquatic avian cute waterfowl",
    "reindeer brown tan white red antlers standing side-view black eyes small four-legged cute pink nose tail hooves simplicity minimalistic warm colors festive",
    "wolf gray white red menacing fangs snarling aggressive left-facing dark eyes ears muzzle sharp teeth animal ferocious canine",
    "sheep white black small quadruped animal woolly side view simplistic cute peaceful four legs tail ears standing",
    "skeleton white black character frontal neutral standing bones humanoid two-dimensional simple compact small illustration figure",
    "snail brown orange shell curled antennae two small crawling side-view simple stylized minimalistic creature terrestrial gastropod",
    "brown orange eight-legged creature abstract simplified front-facing ambivalent segmented body arthropod antennae-like small dark simplistic blocky digital representation minimalistic centered",
    "monochrome white gray black square-shaped symmetrical geometric checkered abstract patterned centered light-to-dark gradient crossing interlacing grid-like",
    "5 star orange yellow gradient five-pointed symmetrical glowing bright centered sharp points warm small shiny solid object",
    "orange white black digital dog standing side-view small brown ears tail four-legged simple squares cute alert",
    "brown square three-dimensional cube stackable patterned textured block shaded digital building game element construction modular geometric symmetrical minecraft iconic resource",
    "white unicorn rainbow mane tail standing profile horn simple geometric small hooves mythical creature multicolored vibrant stationary left-facing quadruped digital",
    "pixelated brown head white eyes open mouth pink tongue teeth rounded dark eyebrows squares blocks simplistic avatar emotion surprised expression",
    "white cat blue eyes pink ears nose sitting tail red collar cute small whiskers front-facing alert fluffy",
    "bunny white pink ears blue eyes cute front-facing whiskers nose small happy simplistic two-teeth cheerful rosy-cheeks",
    "red white checkered candy cane curved right angle vertical horizontal striped corner two-dimensional bent l-shaped contrasting simplistic",
    "zebra white black stripes standing profile view four legs ears tail square minimalistic representation grayscale animal equine abstract simple stylized digital iconic",
    "blue building windows pink door grey roof antenna green tree brown trunk yellow sand sidewalk",
    "campfire orange yellow flames warmth glow dark green logs nighttime burning relaxation outdoors camping light ambiance embers cozy illuminated flickering",
    "castle blue white red towers green brown flag battlements square grass drawbridge vertical fortified structure moat reflection",
    "brown horse small standing side-view light-brown dark-brown mane tail hooves white blaze rectangular simplicity stationary calm four-legged animal tiny flame",
    "red white circus tent miniature icon camping entertainment shelter striped portable festive structure peaked roof fabric collapsible temporary venue vibrant recreational iconic",
    "white gray black red pixel cake layers frosting stripes flame birthday candles lit celebration sweet dessert square food treat cheerful",
    "fire station red gray yellow building miniature windows doors simplified toy-like structure representation emergency service architecture",
    "animated house-shaped face red roof yellow walls green base white windows door happy simplistic square brown chimney front-view",
    "building hospital red white gray cross entrance windows symmetrical flat roof rectangular front view medical",
    "building yellow red windows green roof door symmetrical blocky small simple structure square representation miniature",
    "house red-roof white-walls blue-windows brown-door chimney green-ground small-path simplistic welcoming cozy miniature frontal-view residential architecture warm inviting compact homely shelter",
    "house orange red roof chimney yellow windows door green base",
    "house red blue yellow green door windows roof chimney front-view simplistic small rectangle square vibrant two-story grass",
    "tan brown gray red white black cylindrical cube-shaped animated two figures smiling blue cap metallic antenna checkered pattern large teeth small eyes",
    "chess pieces king queen brown beige ivory contrast crown cross vertical symmetric game strategy classic board standing sturdy elegant timeless",
    "building windows blue tan red door front view small simple blocky symmetrical urban structure facade rectangular entrance",
    "two figures standing blue stripes white shirts short hair brown shoes neutral expression side-by-side front view light skin",
    "buildings skyscrapers blue windows beige multi-story red doors blocky two adjacent urban rectangular flat roofs",
    "cottage orange roof gray walls brown door green base two-story chimney small windows symmetrical cozy simplistic miniature frontal view residential structure",
    "building blue grey green white red square door windows roof small siren urban miniature simple facade architecture structure front-view flat",
    "pixelated cube green white red teeth smiling square mimicking creature blocky monster four-eyed simplistic happy gaming icon fictional character minecraft",
    "building pixelated beige white windows red blue flag symmetrical front-view doorway structure small blocky simplified roof miniature iconic representation",
    "orange brown beige square windows door red front view small structure roof",
    "brown building teal roof rectangular windows yellow front door symmetrical small two-story",
    "chicken white brown red green pixel-image front-view small feathers beak crest eyes standing simplistic cartoonish neutral-expression",
    "cottage brown roof white snow tiny door blue windows front-facing cozy chimney smokeless simplistic design small quaint",
    "dog pixel brown white sitting symmetrical ears up tail short paws front together cute small simple icon",
    "palm tree tropical green brown trunk island yellow sand blue water small simplistic solitary two-dimension nature serene warm colors miniature isolated",
    "animated train cartoon orange blue windows red wheels black square smiling front-view stationary happy brown grey character",
    "ambulance white red blue gray emergency medical cross symbol side-view wheels transportation healthcare service urgent siren vehicle rectangular windows safety",
    "firetruck red white small side-view wheels orange flame gray ladder cabin emergency vehicle",
    "car pixelated blue white yellow side-view simplistic tires gray headlights bumper compact windows roof taillights blocky",
    "car gray small blue red white yellow pixel side-view headlights taillights wheels compact simplistic two-door",
    "mushroom cloud explosion yellow-orange ascending gray blue dynamic powerful billowing ominous heat energy force destructive iconic nuclear alert danger plume fiery",
    "orange helicopter side-view gray rotor tail cockpit skids airborne compact two-blade single-engine transportation flying vehicle rotary-wing",
    "helicopter green side-view rotating blades tail rotor yellow details skids windows cockpit small airborne",
    "colorful ice-cream cone multicolored spheres red orange yellow green blue indigo violet melting drips white cream dessert sweet floating two-bite",
    "red white gray cross horizontal vertical diagonal pixel health gaming icon symbol floating first-aid medical care emergency aid assistance safety",
    "sword brown gray white black crossguard hilt blade pixel-like diagonal shiny small simple iconic item weapon game-related dark-background floating contrast",
    "sword pixelated brown gray tan crossguard hilt blade point centered sharp weapon metallic beige short sturdy combat handle edges diagonal",
    "red white small rocket upward orange flame propulsion floating gray blue window silver cylindrical compact overhead retro combustion travel space",
    "blue bicycle black tires small two-wheeled seat pedals handlebars simplistic side-view transport recreation motionless unisex",
    "red bicycle black tires small simplistic two-wheeled transportation pedal-driven seat handlebars side-view symmetrical recreational compact motion-capable",
    "red car side-view small wheels gray headlights windows dark red bumper simplistic compact stationary transport vehicle shiny shadowed",
    "green car pixel-art side-view black wheels small windows white headlights red taillight simplistic dark-green shading two-door compact reflection square abstract",
    "taxi yellow orange side-view black wheels gray bumper headlights simplistic square compact windows transportation",
    "blue car pixelated small side-view round simplistic dark-blue gray headlights front bumper windows black tires shiny highlights compact curved shadow",
    "red gas pump retro white black gray nozzle hose side view fuel dispenser yellow small window square shape",
    "cat toaster white grey orange yellow flames bread appliance animated ears eyes two slots paws whiskers",
    "green white red yellow gray black vehicle small side-view wheels racing stripes spoiler compact sporty ground stationary glossy_finish racecar number",
    "green tractor small yellow details black tires grey hubcaps side-view red taillight window reflective angled machinery agricultural equipment sturdy utilitarian",
    "traffic light vertical red yellow green illuminated sequence signal control safety regulated intersection lamps pole-mounted traffic-flow management device colors order visibility",
    "truck green orange gray wheels side-view cargo small rectangular headlights simplistic two-dimensional vehicle transportation cargo-box cab dark-green light-orange",
    "truck red orange blue white gray wheels side-view shipping cargo transport trailer cab simplistic stationary small semi heavy-duty",
    "truck red gray yellow wheels cargo side-view simplistic rectangular trailer cab small windows horizontal transport vehicle",
    "green yellow gray monitor lizard small compact side-view reptilian eyes creature tail limbs resting animal",
    "red white boat water blue waves small chimney floating side-view calm static grey shadow underbelly simplistic blocky two-tone railing antenna",
    "sailboat yellow sails white hull red flag blue water floating small waves side view calm simple design",
    "sitting male green shirt brown pants brown hair side profile desk concentrated small simplistic seated indoors focused casual youthful still resting arms calm",
    "sailing ship white sails red flag brown hull masts calm blue water small waves side view",
    "ship red white blue water two funnels floating stationary small waves dark overhead view blocky design",
    "red dark-blue vehicle bus windows wheels blocky simplistic two-tone rectangular side-view transport stationary small gray minimalistic iconic",
    "yellow school bus gray bumper black wheels red taillights side-view horizontal simplistic small windows rectangular transportation",
    "cat gray white small yellow dot lying side-view relaxed curled tail whiskers compact serene four-legged animal",
    "vehicle taxi yellow checkered orange black headlights side-view wheels red taillights gray bumper transportation",
    "train locomotive red black gray smoke wheels yellow side-view small dark chimney rail vehicle transportation",
    "candle flame orange yellow white beige brown vertical glowing illumination wax melting simple warmth light source stationary",
    "beach ball red yellow white blue round inflated colorful striped playful floating buoyant leisure toy summer recreational bright spherical iconic fun",
    "utensil fork silver three-tined prongs upright centered handle functional eating-tool metal reflective flatware dining pronged kitchenware mealtime tool silverware simplicity",
    "golden key metallic shimmer intricate antique teeth left-facing vintage security access ornate small object unlock mystery brass traditional",
    "red balloon floating string curved shiny upward bright round buoyant cheerful vibrant celebration helium-filled party balloon knot levity playful smooth",
    "orange brown spherical sports equipment basketball inflated textured rubber recreation competition play game bouncing round athletic hobby indoor outdoor",
    "spinning top red yellow green circular stripes toy small shadow bright playful object centered symmetric spinning motion blur effect vibrant contrast",
    "spinning top red yellow stripes diagonal magenta handle glow bright centered vibrant contrast dynamic motion toy small reflection shiny playful",
    "blue alien two-legged monster antenna eyes claws standing simple symmetrical cute small fictional character creature smiling friendly whimsical light-blue navy-blue",
    "blue shirt short-sleeved collar buttons light blue dark blue checkered pattern casual front view clothing garment square hem",
    "gray circle simplistic two white dots neutral mouth black small three pixels expressionless front-facing symmetrical floating",
    "character orange red frontal-view small-eyes neutral-expression beige-mouth simplistic standing short-arms hands-down flat-top-head two-toned miniature centered",
    "sword red gray brown gold hilt blade diagonal sharp fantasy weapon",
    "candle flame orange yellow white wax melting lit wick glow warm vertical still small light brown holder base solid",
    "animated character helmet gray visor silver red detail square chinstrap emotionless neutral metallic protective headgear vertical centered two-toned",
    "green beige square front-facing two black eyes open mouth sparse teeth straight-line eyebrows subtle smile small nostrils",
    "chair four-legged wooden brown red seat-cushion upright frontal-view simplistic sturdy traditional design furniture",
    "square brown cookie chocolate chips edible sweet dessert baked treat snack delicious craving homemade sugary indulgence confectionery golden edges warm comfort food",
    "eyeball blue white black circular central iris pupil cornea reflective sphere organic looking glance focused visible eyelid lashes",
    "yellow red simplistic smiling character frontal-view standing round-head minimalistic hands-down two-dimensional cheerful small-eyes short-arms male-figure flat-top iconic bright simplistic-feet",
    "helmet gray gold visor dark metallic reflection faceless headgear frontal protective mysterious glossy contour shaped futuristic accented sleek sturdy",
    "green lime alien pixelated invader video game character space invaders retro blocky two-dimensional iconic symmetrical menacing extraterrestrial arcade simple geometric",
    "sunglasses green black pixel representation two lenses bridge temples eyewear fashion accessory front-facing overhead view nostalgiac iconic minimalistic",
    "crown yellow orange frontal smiling face three spikes top two-tiered eyes simplistic rectangular base happy floating isolated",
    "Cute, lightbulb, character, orange, yellow, white, happy, smiling, idea, bright, illuminated, cartoon, electrical, creativity, glowing, cheerful, mascot, friendly, energetic, shiny",
    "gift box red yellow ribbon bow smiling face anthropomorphic happy present wrapped emoji-like square frontal",
    "trophy gold red smiling front-facing handles symmetrical celebratory shiny standing victory achievement representation reward recognition cup-shaped cheerful reflective prominent",
    "silver key vertical teeth rightward bow top shaft bottom metal shiny cutout secure small simplistic minimalist",
    "key metal grey silver horizontal teeth right-facing bit ward bow compact security unlock access object physical",
    "digital piano keyboard miniature eight white keys green display red indicator light black speaker grills brown case front view",
    "magnifying glass blue gray brown red circular handle reflective centered investigative zooming enlarged-view optical focused looking observing inspecting curiosity clarity tool",
    "microphone gray black blue orange red diagonal handheld interview recording communication audio electronic mesh top handle speaking sound equipment metallic",
    "cube iron block gray white diagonal hammer red brown handle silver tool crafting game item vertical",
    "torch red brown gray gold flame vertical burning wooden handle simplistic bright warm glowing light small handheld",
    "flute brown horizontal musical instrument gold stripes blue red decorative small compact wooden cylindrical handheld",
    "abstract multicolored squares red blue yellow orange green purple black chaotic scattered small clustered bright vivid contrast",
    "pencil diagonal yellow pink eraser brown pointed tip writing instrument graphite wooden hexagonal barrel",
    "pencil icon yellow gray white eraser diagonal writing brown sharp point editing office school tool graphite wood",
    "red orange brown diagonal glowing gradient white square sharp tip handle",
    "crossed swords orange yellow grey hilt diagonal intersecting sharp weapon simple metallic",
    "piano keyboard white keys black keys musical instrument brown horizontal melody harmony octave pattern alternating ivory ebony red stripe classic",
    "potion green bottle white cap yellow sparkles happy face red cheeks smiling floating liquid translucent two eyes",
    "potion blue liquid smiling face white bubbles orange cap front view happy clear glass curved bottle shiny",
    "potion orange yellow bubbles sparkling flask cork grey content happy front-view glowing curved floating shiny round transparent gradient effervescent",
    "gift red green ribbon bow box present celebration festive wrapped square-shaped shiny two-tone contrast rectangular-shadow",
    "gift red yellow green bow ribbon box wrapped present shining pixel-art bright small festive square-shaped tied top-view",
    "pixelated mushroom purple white vertical stripes cap stem simplistic two-dimensional icon video game item",
    "camera red black grey yellow lens flash strap viewfinder square button nostalgic capture film portable photography equipment object iconic detailed",
    "red character two-legged simplistic arcade alien crab-like white eyes aggressive claws video game invader enemy frontal view ominous small antennae iconic",
    "glasses red square-shaped thick frames clear lenses black outline grey interior symmetrical centered two earpieces fashion accessory front view simple design",
    "red umbrella brown handle curved top-view black accents small simple symmetrical protective accessory weather-related",
    "gold saxophone musical instrument shiny brass curved bell keys black accents blowing end small details airflow opening cylindrical mouthpiece",
    "character white hair gray beard black eyes red pants white shoes front view neutral expression small ears standing",
    "sled red green brown gold small side-view simple festive stationary object curved holiday traditional wooden metallic shiny runners classic toy",
    "candy cane red white striped curved small shiny light blue reflections floating sweet festive diagonal orientation treat sugary",
    "red white stripes abstract geometric four rectangles l-shaped blocks connected contrasting simple bold candy-cane pattern right-angle stacked horizontal vertical diagonal",
    "red orange white blocky horizontal stripes shaded shiny reflective curved top flat bottom",
    "yellow green character antenna robotic head square red button gray sides abstract facial features simplistic small front-facing expressionless",
    "brown chest lock pixel-art storage container wooden secure treasure item game asset front-view gold handle square lid closed object blocky",
    "man facial hair brown smoking pipe orange side-view serene gray white small square simplicity",
    "walking cane brown diagonal curved handle simplistic dark background solitary object item accessory support no people leaning right side up",
    "appliance washing machine white gray window blue clothing visible front-loading square dark round dial buttons small compact household modern essential front",
    "green grey red pixel robot antenna right-facing four legs two eyes small boxy simplistic",
    "books red green orange yellow blue light blue brown shelf standing vertical colorful lined up bright small medium large",
    "yellow alien space invaders iconic video game character blocky two antennas invader alien aggressive frontal view simple menacing classic extraterrestrial",
    "yellow jacket white shirt blue stripes front-facing icon small simple unisex clothing fashion outerwear bright casual collar zipped cuffs pockets",
    "sunrise orange yellow white blue ocean horizon tranquil warm dusk square gradient serene twilight reflection",
];

const activeIcons: number[] = [];

function filterIcons(term: string) {
    while (activeIcons.length) {
        const el = iconsEl.children[activeIcons.pop()];
        el.className = el.className.replace(" active", "");
    }
    for (let i = 0; i < keywords.length; i++) {
        if (keywords[i].indexOf(term) !== -1) {
            const el = iconsEl.children[i];
            el.className += " active";
            activeIcons.push(i);
        }
    }
    iconsEl.className = activeIcons.length ? "filtered" : "";
}

const handleKeyupEvent = (event: KeyboardEvent) => filterIcons((event.target as HTMLInputElement).value.toLocaleLowerCase());

const debouncedKeyupEvent = (() => {
    let timeoutId: number;

    return function (event: KeyboardEvent) {
        clearTimeout(timeoutId);
        timeoutId = window.setTimeout(() => {
            handleKeyupEvent(event);
        }, 5);
    };
})();

searchEl.addEventListener("keyup", debouncedKeyupEvent);

let lastKnownScrollPosition = 0;
let ticking = false;
const minScrollY = 200;

function moveSearchbox(y: number) {
    if (y < minScrollY) {
        formPlaceholderEl.style.display = "none";
        formEl.style.position = "";
        return;
    }

    formPlaceholderEl.style.display = "block";
    formEl.style.position = "absolute";
    formEl.style.top = `${y - minScrollY}px`;
}

document.addEventListener("scroll", (event) => {
    lastKnownScrollPosition = window.scrollY;

    if (!ticking) {
        window.requestAnimationFrame(() => {
            moveSearchbox(lastKnownScrollPosition);
            ticking = false;
        });

        ticking = true;
    }
});

function createIcons() {
    for (let i = 0; i < keywords.length; i++) {
        const y = Math.floor(i / 10);
        const x = i % 10;
        const el = document.createElement("img");
        // el.src = `img/sprite_${y}_${x}.png`;
        el.alt = "";
        el.title = keywords[i];
        el.className = `x-${x} y-${y}`;
        iconsEl.appendChild(el);
    }
}

createIcons();

// Generate CSS rules for sprite background image positions.
// let str = "";
// for (let x = 1; x < 10; x++) {
//     str += `/* prettier-ignore */\n.x-${x} { background-position-x: -${48 * x}px; }\n`;
// }
// for (let y = 1; y < 57; y++) {
//     str += `/* prettier-ignore */\n.y-${y} { background-position-y: -${48 * y}px; }\n`;
// }
// console.log(str);

// Fixes TS2451: Cannot redeclare block-scoped variable
export {};
